# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4423fd6ab3ad2f284af755effa358bad2f0e9989752d2ca5990b4d95303b369d7b447c5ac7fc88657360cf7ccb3679554c26ec79345dcce350b2f9f1e3069e17

test:
  secret_key_base: c89d082d6d99339bc98c2adb8c52cbe57b4b9133b753c9079bc8382371f679d44cda06a420619d1e8c18e09ad267c23cd22a4c1a0a800b8ff98097e6227b1b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
